K_epochs: 80
action_std: 0.6
action_std_decay_freq: 250000
action_std_decay_rate: 0.05
eps_clip: 0.2
gamma: 0.99
lr_actor: 0.0003
lr_critic: 0.001
max_ep: 1000
max_train_timestemps: 3000000
min_action_std: 0.1
print_freq: 2000
render: true
render_freq: 50
run_name: ppo_2025-03-25_17-05-51
save_model_freq: 10000
update_timestep: 4000
screen_width: 1000
screen_height: 700
sensor_dim: 5
num_checkpoints: 80
track_width: 80
track_radius: 300